// Generated by /from-issue on 2026-06-01 from Jira SW-6.
// Source: https://diegocortes15.atlassian.net/browse/SW-6
// Title: [SW][QA][Inventory] User can add products to cart
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { products } from '@data/fixtures';

const BACKPACK = 'Sauce Labs Backpack';
const BIKE_LIGHT = 'Sauce Labs Bike Light';
const BOLT_TSHIRT = 'Sauce Labs Bolt T-Shirt';
const backpack = products.find((p) => p.name === BACKPACK)!;

test.describe('cart — standard_user', { tag: '@standard' }, () => {
  test.describe('Positive', () => {
    // AC 1
    test('adding a product shows a cart badge count of one', { tag: '@smoke' }, async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await expect.poll(() => inventoryPage.getCartBadgeCount()).toBe(1);
    });

    // AC 2 + AC 3 (merged): one add-three flow proves both the badge count and
    // that the cart lists the products in the order they were added.
    test('adding three products shows a badge of three and lists them in add order', async ({
      inventoryPage,
      cartPage,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.addToCart(BIKE_LIGHT);
      await inventoryPage.addToCart(BOLT_TSHIRT);
      await expect.poll(() => inventoryPage.getCartBadgeCount()).toBe(3);

      await inventoryPage.openCart();
      await expect
        .poll(() => cartPage.getItemNames())
        .toEqual([BACKPACK, BIKE_LIGHT, BOLT_TSHIRT]);
    });

    // AC 4
    test('a cart row shows the quantity, title, description, price, and a remove button', async ({
      inventoryPage,
      cartPage,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();

      expect(await cartPage.getItemNames()).toContain(BACKPACK);
      expect(await cartPage.getItemQuantity(BACKPACK)).toBe('1');
      expect(await cartPage.getItemDescription(BACKPACK)).toBe(backpack.description);
      expect(await cartPage.getItemPrice(BACKPACK)).toBe(backpack.price);
      expect(await cartPage.hasRemoveButton(BACKPACK)).toBe(true);
    });

    // AC 5
    test('removing a product drops it from the cart and decrements the badge', async ({
      inventoryPage,
      cartPage,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.addToCart(BIKE_LIGHT);
      await inventoryPage.openCart();
      await expect.poll(() => cartPage.getCartBadgeCount()).toBe(2);

      await cartPage.removeItem(BACKPACK);
      await expect.poll(() => cartPage.getItemNames()).toEqual([BIKE_LIGHT]);
      await expect.poll(() => cartPage.getCartBadgeCount()).toBe(1);
    });

    // AC 6
    test('continue shopping returns to the inventory page', async ({
      inventoryPage,
      cartPage,
      page,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();

      await cartPage.continueShopping();
      await expect(page).toHaveURL(/\/inventory\.html$/);
    });
  });

  test.describe('Edge', () => {
    // AC 7
    test('removing the last item hides the cart badge', async ({ inventoryPage, cartPage }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();

      await cartPage.removeItem(BACKPACK);
      // The cart is empty: saucedemo removes the badge element entirely (count 0).
      await expect.poll(() => cartPage.getCartBadgeCount()).toBe(0);
      await expect.poll(() => cartPage.getItemCount()).toBe(0);
    });

    // AC 8
    test('adding a product toggles its inventory button to Remove', async ({ inventoryPage }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      // saucedemo caps quantity at 1 per product — the Add button becomes Remove.
      await expect.poll(() => inventoryPage.getProductButtonLabel(BACKPACK)).toBe('Remove');
    });

    // AC 9
    test('cart contents persist after continue shopping', async ({ inventoryPage, cartPage }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();
      await cartPage.continueShopping();

      await inventoryPage.openCart();
      await expect.poll(() => cartPage.getItemNames()).toEqual([BACKPACK]);
      await expect.poll(() => cartPage.getCartBadgeCount()).toBe(1);
    });
  });
});
