// Generated by /from-issue on 2026-05-23 from GitHub Issue #7.
// Source: https://github.com/Diegocortes15/playwright-ia-automation-framework-saucedemo/issues/7
// Title: [SDA][Login] Login in Saucedemo App
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against the same issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { env } from '@utils/env';

const validUsers = [
  'standard_user',
  'problem_user',
  'performance_glitch_user',
  'error_user',
  'visual_user',
] as const;

const invalidCredentialScenarios = [
  {
    name: 'submitting empty credentials shows "username is required" error',
    smoke: false,
    username: '',
    password: '',
    expectedError: 'Epic sadface: Username is required',
  },
  {
    name: 'submitting only password shows "username is required" error',
    smoke: false,
    username: '',
    password: 'secret_sauce',
    expectedError: 'Epic sadface: Username is required',
  },
  {
    name: 'submitting only username shows "password is required" error',
    smoke: false,
    username: 'standard_user',
    password: '',
    expectedError: 'Epic sadface: Password is required',
  },
  {
    name: 'submitting invalid credentials shows "do not match" error',
    smoke: true,
    username: 'invalid_user',
    password: 'wrong_password',
    expectedError: 'Epic sadface: Username and password do not match any user in this service',
  },
];

test.describe('login @no-auth', () => {
  test.describe('Positive', () => {
    for (const user of validUsers) {
      const smokePrefix = user === 'standard_user' ? '@smoke ' : '';

      test(`${smokePrefix}${user} logs in successfully and lands on inventory page`, async ({
        loginPage,
        page,
      }) => {
        await loginPage.goto();
        await loginPage.loginAs(user, env.password);
        await expect(page).toHaveURL(/\/inventory\.html$/);
      });
    }
  });

  test.describe('Negative', () => {
    for (const scenario of invalidCredentialScenarios) {
      const smokePrefix = scenario.smoke ? '@smoke ' : '';

      test(`${smokePrefix}${scenario.name}`, async ({ loginPage }) => {
        await loginPage.goto();
        await loginPage.loginAs(scenario.username, scenario.password);
        await expect(loginPage.errorBanner).toBeVisible();
        expect(await loginPage.getErrorText()).toContain(scenario.expectedError);
      });
    }
  });
});
