// Generated by /from-issue on 2026-05-24 from GitHub Issue #7.
// Source: https://github.com/Diegocortes15/playwright-ia-automation-framework-saucedemo/issues/7
// Title: [SDA][Login] Login in Saucedemo App
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against the same issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { env } from '@utils/env';

test.describe('login @no-auth', () => {
  test.describe('Positive', () => {
    // Scenario 1: every accepted (non-locked-out) user authenticates and lands
    // on the inventory page. One parameterized test per user (F.I.R.S.T. isolation).
    const loginUsers = [
      'standard_user',
      'problem_user',
      'performance_glitch_user',
      'error_user',
      'visual_user',
    ];

    for (const user of loginUsers) {
      // standard_user is the smoke gateway; the other valid users are
      // configuration variations of the same flow (smoke-policy.md).
      const smokePrefix = user === 'standard_user' ? '@smoke ' : '';

      test(`${smokePrefix}${user} logs in successfully and lands on the inventory page`, async ({
        loginPage,
        page,
      }) => {
        await loginPage.goto();
        await loginPage.loginAs(user, env.password);
        await expect(page).toHaveURL(/\/inventory\.html$/);
      });
    }
  });

  test.describe('Negative', () => {
    // Scenarios 2 & 3: missing required fields. saucedemo validates username
    // before password, so an empty username always wins the error message.
    const requiredFieldCases = [
      {
        username: '',
        password: '',
        error: 'Epic sadface: Username is required',
        desc: 'no credentials',
      },
      {
        username: 'standard_user',
        password: '',
        error: 'Epic sadface: Password is required',
        desc: 'missing password',
      },
      {
        username: '',
        password: env.password,
        error: 'Epic sadface: Username is required',
        desc: 'missing username',
      },
    ];

    for (const { username, password, error, desc } of requiredFieldCases) {
      test(`${desc} shows the required-field error`, async ({ loginPage }) => {
        await loginPage.goto();
        await loginPage.loginAs(username, password);
        await expect(loginPage.errorBanner).toBeVisible();
        expect(await loginPage.getErrorText()).toBe(error);
      });
    }

    // Scenario 4: well-formed but unrecognized credentials are rejected with a
    // generic error (no user enumeration). Core auth-rejection smoke check.
    test('@smoke invalid credentials are rejected with a generic error', async ({ loginPage }) => {
      await loginPage.goto();
      await loginPage.loginAs('invalid_user', 'wrong_password');
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toBe(
        'Epic sadface: Username and password do not match any user in this service',
      );
    });
  });
  // Edge describe omitted — no edge tests for this issue.
});
