// Generated by /from-issue on 2026-05-21 from GitHub Issue #5.
// Source: https://github.com/Diegocortes15/playwright-ia-automation-framework-saucedemo/issues/5
// Title: [TBA] Login coverage with smoke selection
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against the same issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { env } from '@utils/env';

test.describe('login (@no-auth)', () => {
  test.describe('Positive', () => {
    test('@no-auth @smoke standard_user logs in with valid credentials and lands on inventory', async ({
      loginPage,
      page,
    }) => {
      // Arrange
      await loginPage.goto();
      // Act
      await loginPage.loginAs('standard_user', env.password);
      // Assert
      await expect(page).toHaveURL(/\/inventory\.html$/);
    });
  });

  test.describe('Negative', () => {
    test('@no-auth @smoke locked_out_user sees the lockout error message', async ({
      loginPage,
    }) => {
      // Arrange
      await loginPage.goto();
      // Act
      await loginPage.loginAs('locked_out_user', env.password);
      // Assert
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toContain('locked out');
    });

    test('@no-auth standard_user invalid password shows a generic error message', async ({
      loginPage,
    }) => {
      // Arrange
      await loginPage.goto();
      // Act
      await loginPage.loginAs('standard_user', 'wrong_password');
      // Assert
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toContain('Username and password do not match');
    });
  });

  test.describe('Edge', () => {
    test('@no-auth standard_user username with leading whitespace is rejected', async ({
      loginPage,
    }) => {
      // Arrange
      await loginPage.goto();
      // Act
      await loginPage.loginAs(' standard_user', env.password);
      // Assert
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toContain('Username and password do not match');
    });
  });
});
