// Generated by /from-issue on 2026-05-25 from Jira SW-1.
// Source: https://diegocortes15.atlassian.net/browse/SW-1
// Title: [SW][QA][Login] Login in Saucedemo App
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { env } from '@utils/env';

test.describe('login @no-auth', () => {
  test.describe('Positive', () => {
    // Scenario 1: every valid user logs in and lands on the Products page.
    const validUsers = [
      'standard_user',
      'problem_user',
      'performance_glitch_user',
      'error_user',
      'visual_user',
    ];

    for (const user of validUsers) {
      // Keep the smoke set tight: only the canonical standard_user gates builds.
      const smoke = user === 'standard_user' ? '@smoke ' : '';
      test(`${smoke}${user} logs in successfully and lands on inventory`, async ({
        loginPage,
        page,
      }) => {
        await loginPage.goto();
        await loginPage.loginAs(user, env.password);
        await expect(page).toHaveURL(/\/inventory\.html$/);
      });
    }
  });

  test.describe('Negative', () => {
    // Scenarios 2 + 3: missing required fields surface the right validation error.
    const requiredFieldCases = [
      {
        username: '',
        password: '',
        error: 'Epic sadface: Username is required',
        desc: 'no credentials',
      },
      {
        username: 'standard_user',
        password: '',
        error: 'Epic sadface: Password is required',
        desc: 'missing password',
      },
      {
        username: '',
        password: env.password,
        error: 'Epic sadface: Username is required',
        desc: 'missing username',
      },
    ];

    for (const { username, password, error, desc } of requiredFieldCases) {
      test(`${desc} shows the required-field error`, async ({ loginPage }) => {
        await loginPage.goto();
        await loginPage.loginAs(username, password);
        await expect(loginPage.errorBanner).toBeVisible();
        await expect(loginPage.errorBanner).toHaveText(error);
      });
    }

    // Scenario 4: invalid credentials are rejected with the standard error.
    test('@smoke invalid credentials are rejected', async ({ loginPage }) => {
      await loginPage.goto();
      await loginPage.loginAs('invalid_user', 'wrong_password');
      await expect(loginPage.errorBanner).toBeVisible();
      await expect(loginPage.errorBanner).toHaveText(
        'Epic sadface: Username and password do not match any user in this service',
      );
    });
  });
  // Edge describe omitted — no edge tests for this issue.
});
