// Generated by /from-issue on 2026-05-21 from GitHub Issue #3.
// Source: https://github.com/Diegocortes15/playwright-ia-automation-framework-saucedemo/issues/3
// Title: [TBA] Login coverage with all three buckets
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against the same issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { env } from '@utils/env';

test.describe('login (@no-auth)', () => {
  test.describe('Positive', () => {
    test('@no-auth standard_user logs in successfully and lands on inventory', async ({
      loginPage,
      page,
    }) => {
      // Arrange
      await loginPage.goto();
      // Act
      await loginPage.loginAs('standard_user', env.password);
      // Assert
      await expect(page).toHaveURL(/\/inventory\.html$/);
    });
  });

  test.describe('Negative', () => {
    test('@no-auth locked_out_user sees the lockout error', async ({ loginPage }) => {
      // Arrange
      await loginPage.goto();
      // Act
      await loginPage.loginAs('locked_out_user', env.password);
      // Assert
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toContain('locked out');
    });

    test('@no-auth standard_user invalid password shows generic error', async ({ loginPage }) => {
      // Arrange
      await loginPage.goto();
      // Act
      await loginPage.loginAs('standard_user', 'wrong_password');
      // Assert
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toContain('Username and password do not match');
    });
  });

  test.describe('Edge', () => {
    test('@no-auth username with leading whitespace is rejected', async ({ loginPage }) => {
      // Arrange
      await loginPage.goto();
      // Act
      await loginPage.loginAs(' standard_user', env.password);
      // Assert
      await expect(loginPage.errorBanner).toBeVisible();
    });
  });
});
