// Generated by /from-issue on 2026-05-23 from GitHub Issue #7.
// Source: https://github.com/Diegocortes15/playwright-ia-automation-framework-saucedemo/issues/7
// Title: [SDA][Login] Login in Saucedemo App
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against the same issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { env } from '@utils/env';

const successUsers = [
  { user: 'standard_user', smoke: true },
  { user: 'problem_user', smoke: false },
  { user: 'performance_glitch_user', smoke: false },
  { user: 'error_user', smoke: false },
  { user: 'visual_user', smoke: false },
];

const missingCredsCases = [
  {
    label: 'empty username and password',
    username: '',
    password: '',
    expectedError: 'Epic sadface: Username is required',
  },
  {
    label: 'missing username with password provided',
    username: '',
    password: 'secret_sauce',
    expectedError: 'Epic sadface: Username is required',
  },
  {
    label: 'missing password with username provided',
    username: 'standard_user',
    password: '',
    expectedError: 'Epic sadface: Password is required',
  },
];

test.describe('login (@no-auth)', () => {
  test.describe('Positive', () => {
    for (const { user, smoke } of successUsers) {
      const title = smoke
        ? `@no-auth @smoke ${user} logs in successfully and lands on inventory`
        : `@no-auth ${user} logs in successfully and lands on inventory`;
      test(title, async ({ loginPage, page }) => {
        await loginPage.goto();

        await loginPage.loginAs(user, env.password);

        await expect(page).toHaveURL(/\/inventory\.html$/);
      });
    }
  });

  test.describe('Negative', () => {
    for (const { label, username, password, expectedError } of missingCredsCases) {
      test(`@no-auth ${label} shows ${expectedError}`, async ({ loginPage }) => {
        await loginPage.goto();

        if (username) await loginPage.fillUsername(username);
        if (password) await loginPage.fillPassword(password);
        await loginPage.clickLogin();

        await expect(loginPage.errorBanner).toBeVisible();
        await expect(loginPage.errorBanner).toContainText(expectedError);
      });
    }

    test('@no-auth @smoke invalid credentials show authentication error', async ({ loginPage }) => {
      await loginPage.goto();

      await loginPage.loginAs('not_a_real_user', 'wrong_password');

      await expect(loginPage.errorBanner).toBeVisible();
      await expect(loginPage.errorBanner).toContainText(
        'Epic sadface: Username and password do not match any user in this service',
      );
    });
  });
});
