// Generated by /from-issue on 2026-05-23 from GitHub Issue #7.
// Source: https://github.com/Diegocortes15/playwright-ia-automation-framework-saucedemo/issues/7
// Title: [SDA][Login] Login in Saucedemo App
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against the same issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { env } from '@utils/env';

const otherValidUsers = [
  'problem_user',
  'performance_glitch_user',
  'error_user',
  'visual_user',
] as const;

const missingFieldScenarios = [
  {
    description: 'empty password',
    username: 'standard_user',
    password: '',
    expectedError: 'Epic sadface: Password is required',
  },
  {
    description: 'empty username',
    username: '',
    password: 'secret_sauce',
    expectedError: 'Epic sadface: Username is required',
  },
] as const;

test.describe('login (@no-auth)', () => {
  test.describe('Positive', () => {
    test('@no-auth @smoke standard_user logs in successfully and lands on inventory', async ({
      loginPage,
      page,
    }) => {
      await loginPage.goto();
      await loginPage.loginAs('standard_user', env.password);
      await expect(page).toHaveURL(/\/inventory\.html$/);
    });

    for (const username of otherValidUsers) {
      test(`@no-auth ${username} logs in successfully and lands on inventory`, async ({
        loginPage,
        page,
      }) => {
        await loginPage.goto();
        await loginPage.loginAs(username, env.password);
        await expect(page).toHaveURL(/\/inventory\.html$/);
      });
    }
  });

  test.describe('Negative', () => {
    test('@no-auth @smoke empty credentials show "Username is required" error', async ({
      loginPage,
    }) => {
      await loginPage.goto();
      await loginPage.loginAs('', '');
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toContain('Epic sadface: Username is required');
    });

    for (const { description, username, password, expectedError } of missingFieldScenarios) {
      const errorTail = expectedError.replace('Epic sadface: ', '');
      test(`@no-auth ${description} shows "${errorTail}" error`, async ({ loginPage }) => {
        await loginPage.goto();
        await loginPage.loginAs(username, password);
        await expect(loginPage.errorBanner).toBeVisible();
        expect(await loginPage.getErrorText()).toContain(expectedError);
      });
    }

    test('@no-auth @smoke invalid credentials show "do not match" error', async ({
      loginPage,
    }) => {
      await loginPage.goto();
      await loginPage.loginAs('invalid_user', 'wrong_password');
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toContain(
        'Epic sadface: Username and password do not match any user in this service',
      );
    });
  });
});
