// Generated by /from-issue on 2026-05-23 from GitHub Issue #7.
// Source: https://github.com/Diegocortes15/playwright-ia-automation-framework-saucedemo/issues/7
// Title: [SDA][Login] Login in Saucedemo App
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against the same issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { env } from '@utils/env';

test.describe('login (@no-auth)', () => {
  test.describe('Positive', () => {
    test('@no-auth @smoke standard_user logs in successfully and lands on inventory', async ({
      loginPage,
      page,
    }) => {
      await loginPage.goto();
      await loginPage.loginAs('standard_user', env.password);
      await expect(page).toHaveURL(/\/inventory\.html$/);
    });
  });

  test.describe('Negative', () => {
    test('@no-auth empty username and password shows username-required error', async ({
      loginPage,
    }) => {
      await loginPage.goto();
      await loginPage.clickLogin();
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toContain(
        'Epic sadface: Username is required',
      );
    });

    test('@no-auth missing password shows password-required error', async ({
      loginPage,
    }) => {
      await loginPage.goto();
      await loginPage.fillUsername('standard_user');
      await loginPage.clickLogin();
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toContain(
        'Epic sadface: Password is required',
      );
    });

    test('@no-auth missing username shows username-required error', async ({
      loginPage,
    }) => {
      await loginPage.goto();
      await loginPage.fillPassword(env.password);
      await loginPage.clickLogin();
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toContain(
        'Epic sadface: Username is required',
      );
    });

    test('@no-auth invalid credentials show username-password-mismatch error', async ({
      loginPage,
    }) => {
      await loginPage.goto();
      await loginPage.loginAs('not_a_real_user', 'wrong_password');
      await expect(loginPage.errorBanner).toBeVisible();
      expect(await loginPage.getErrorText()).toContain(
        'Epic sadface: Username and password do not match any user in this service',
      );
    });
  });
});
