// Generated by /scaffold-page-object on 2026-05-26.
// Tests using this Page Object are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { test, type Locator, type Page } from '@playwright/test';
import { Footer } from '@components/Footer';

export class InventoryPage {
  // Composed components first (ADR-0001 rule #6).
  readonly footer: Footer;
  // Page-direct locators second.
  private readonly productImages: Locator;
  private readonly productNames: Locator;
  private readonly productDescriptions: Locator;
  private readonly productPrices: Locator;
  private readonly addToCartButtons: Locator;
  // Sort control — saucedemo's ordering control is a native <select> (no separate
  // filter widget); activeSortOption mirrors the currently-selected option's label.
  private readonly sortDropdown: Locator;
  private readonly activeSortOption: Locator;

  constructor(public readonly page: Page) {
    this.footer = new Footer(page);
    this.productImages = page.locator('img.inventory_item_img');
    this.productNames = page.locator('[data-test="inventory-item-name"]');
    this.productDescriptions = page.locator('[data-test="inventory-item-desc"]');
    this.productPrices = page.locator('[data-test="inventory-item-price"]');
    this.addToCartButtons = page.getByRole('button', { name: /^Add to cart$/i });
    this.sortDropdown = page.locator('[data-test="product-sort-container"]');
    this.activeSortOption = page.locator('[data-test="active-option"]');
  }

  // Composed / intent-level action — body wrapped in exactly one test.step.
  async goto(): Promise<void> {
    await test.step('Navigate to the inventory page', async () => {
      await this.page.goto('/inventory.html');
    });
  }

  // Query — returns data, never a Locator (ADR-0001 rule #8).
  async getProductImageSources(): Promise<string[]> {
    return this.productImages.evaluateAll((imgs) =>
      imgs.map((img) => img.getAttribute('src') ?? ''),
    );
  }

  async getProductNames(): Promise<string[]> {
    return (await this.productNames.allTextContents()).map((name) => name.trim());
  }

  async getProductDescriptions(): Promise<string[]> {
    return (await this.productDescriptions.allTextContents()).map((desc) => desc.trim());
  }

  async getProductPrices(): Promise<string[]> {
    return (await this.productPrices.allTextContents()).map((price) => price.trim());
  }

  async getAddToCartButtonCount(): Promise<number> {
    return this.addToCartButtons.count();
  }

  async getEnabledAddToCartButtonCount(): Promise<number> {
    return this.addToCartButtons.evaluateAll(
      (buttons) => buttons.filter((button) => !(button as HTMLButtonElement).disabled).length,
    );
  }

  // Exact-match title locator — substring hasText could match two cards when one
  // product name contains another (per playwright-conventions.md "Exact-match for
  // named-element filters").
  private productTitle(productName: string): Locator {
    return this.page.getByText(productName, { exact: true });
  }

  // Computed text color of a single product's title — used to verify the hover state.
  async getProductTitleColor(productName: string): Promise<string> {
    return this.productTitle(productName).evaluate((el) => getComputedStyle(el).color);
  }

  // Composed action — wrapped in exactly one test.step (playwright-conventions).
  async hoverProductTitle(productName: string): Promise<void> {
    await test.step(`Hover the "${productName}" product title`, async () => {
      await this.productTitle(productName).hover();
    });
  }

  // Composed action — selects a sort option by its <option> value
  // (az | za | lohi | hilo). Native <select>, so selectOption sets it directly.
  async sortBy(optionValue: string): Promise<void> {
    await test.step(`Sort products by "${optionValue}"`, async () => {
      await this.sortDropdown.selectOption(optionValue);
    });
  }

  // Query — the label of the currently-selected sort option (ADR-0001 rule #8).
  async getActiveSortLabel(): Promise<string> {
    return (await this.activeSortOption.textContent())?.trim() ?? '';
  }
}
