// Generated by /scaffold-page-object on 2026-05-26.
// Tests using this Page Object are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { test, type Page } from '@playwright/test';
import { Footer } from '@components/Footer';

export class InventoryPage {
  // Composed components first (ADR-0001 rule #6).
  readonly footer: Footer;

  constructor(public readonly page: Page) {
    this.footer = new Footer(page);
  }

  // Composed / intent-level action — body wrapped in exactly one test.step.
  async goto(): Promise<void> {
    await test.step('Navigate to the inventory page', async () => {
      await this.page.goto('/inventory.html');
    });
  }
}
