// Generated by /scaffold-page-object on 2026-05-25.
// Tests using this Page Object are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { test, type Locator, type Page } from '@playwright/test';

export class LoginPage {
  // Page-direct locators
  readonly usernameInput: Locator;
  readonly passwordInput: Locator;
  readonly loginButton: Locator;
  readonly errorBanner: Locator;

  constructor(public readonly page: Page) {
    this.usernameInput = page.locator('[data-test="username"]');
    this.passwordInput = page.locator('[data-test="password"]');
    this.loginButton = page.locator('[data-test="login-button"]');
    this.errorBanner = page.locator('[data-test="error"]');
  }

  // Primitives — single-element actions, never wrapped in test.step.
  async fillUsername(value: string): Promise<void> {
    await this.usernameInput.fill(value);
  }

  async fillPassword(value: string): Promise<void> {
    await this.passwordInput.fill(value);
  }

  async clickLogin(): Promise<void> {
    await this.loginButton.click();
  }

  // Composed / intent-level actions — body wrapped in exactly one test.step.
  async goto(): Promise<void> {
    await test.step('Navigate to the login page', async () => {
      await this.page.goto('/');
    });
  }

  async loginAs(username: string, password: string): Promise<void> {
    await test.step('Submit credentials', async () => {
      await this.usernameInput.fill(username);
      await this.passwordInput.fill(password);
      await this.loginButton.click();
    });
  }

  // Query — returns data, never a Locator (ADR-0001 rule #8).
  async getErrorText(): Promise<string> {
    return (await this.errorBanner.textContent())?.trim() ?? '';
  }
}
