// Generated by /scaffold-page-object on 2026-09-06.
// Tests using this Page Object are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { test, type Locator, type Page } from '@playwright/test';
import { Footer } from '@components/Footer';
import { Header } from '@components/Header';

export class ProductDetailPage {
  // Composed components first (ADR-0001 rule #6).
  readonly footer: Footer;
  readonly header: Header;
  // Page-direct locators second. Every one resolved to a data-test attribute —
  // each was checked against the rendered DOM rather than read off the snapshot
  // (selector order #1, no downgrades).
  private readonly productName: Locator;
  private readonly productDescription: Locator;
  private readonly productPrice: Locator;
  private readonly addToCartButton: Locator;
  private readonly backToProductsButton: Locator;

  constructor(public readonly page: Page) {
    this.footer = new Footer(page);
    this.header = new Header(page);
    this.productName = page.locator('[data-test="inventory-item-name"]');
    this.productDescription = page.locator('[data-test="inventory-item-desc"]');
    this.productPrice = page.locator('[data-test="inventory-item-price"]');
    this.addToCartButton = page.locator('[data-test="add-to-cart"]');
    this.backToProductsButton = page.locator('[data-test="back-to-products"]');
  }

  // Composed / intent-level action — body wrapped in exactly one test.step.
  // saucedemo addresses a detail page by numeric id, not by product name
  // (/inventory-item.html?id=4 is the Sauce Labs Backpack). Tests that start
  // from the inventory page should use InventoryPage.openProductDetail(name)
  // instead, so the id stays out of the spec.
  async goto(productId: number): Promise<void> {
    await test.step(`Navigate to the product detail page for id ${productId}`, async () => {
      await this.page.goto(`/inventory-item.html?id=${productId}`);
    });
  }

  // Queries — return data, never a Locator (ADR-0001 rule #8).
  async getProductName(): Promise<string> {
    return (await this.productName.textContent())?.trim() ?? '';
  }

  async getProductDescription(): Promise<string> {
    return (await this.productDescription.textContent())?.trim() ?? '';
  }

  async getProductPrice(): Promise<string> {
    return (await this.productPrice.textContent())?.trim() ?? '';
  }

  // Query — cart count from the header badge; 0 when the badge is absent.
  // Mirrors InventoryPage.getCartBadgeCount().
  async getCartBadgeCount(): Promise<number> {
    return this.header.getCartItemCount();
  }

  // Primitives — single-element actions, NOT wrapped in test.step (Playwright
  // already records the underlying click).
  async clickAddToCart(): Promise<void> {
    await this.addToCartButton.click();
  }

  async clickBackToProducts(): Promise<void> {
    await this.backToProductsButton.click();
  }
}
