// Generated by /from-issue on 2026-05-27 from Jira SW-3.
// Source: https://diegocortes15.atlassian.net/browse/SW-3
// Title: [SW][QA][Inventory] problem_user sees broken product images
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';

// problem_user is one of saucedemo's intentionally-broken accounts: the inventory
// page serves the same placeholder image (sl-404) for every product instead of a
// distinct image per product. This characterization test locks that defect in.
test.describe('inventory — problem_user', { tag: '@problem' }, () => {
  test.describe('Edge', () => {
    test('problem_user sees one identical broken image for every product', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      const sources = await inventoryPage.getProductImageSources();
      // Every product image collapses to a single shared src (the broken
      // placeholder) instead of a distinct image per product.
      expect(sources.length).toBeGreaterThan(0);
      expect(new Set(sources).size).toBe(1);
    });
  });
});
