// Generated by /from-issue on 2026-05-27 from Jira SW-3.
// Source: https://diegocortes15.atlassian.net/browse/SW-3
// Title: [SW][QA][Inventory] problem_user sees broken product images
// Augmented by: SW-4 (2026-05-27), SW-5 (2026-05-30)
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { products } from '@data/fixtures';

// problem_user is one of saucedemo's intentionally-broken accounts: the inventory
// page serves the same placeholder image (sl-404) for every product instead of a
// distinct image per product. This characterization test locks that defect in.
test.describe('inventory — problem_user', { tag: '@problem' }, () => {
  test.describe('Edge', () => {
    test('problem_user sees one identical broken image for every product', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      const sources = await inventoryPage.getProductImageSources();
      // Every product image collapses to a single shared src (the broken
      // placeholder) instead of a distinct image per product.
      expect(sources.length).toBeGreaterThan(0);
      expect(new Set(sources).size).toBe(1);
    });
  });
});

// standard_user sees the canonical, fully-rendered inventory: 6 products, each
// with a distinct image, exact title/description, $-formatted price, and an
// enabled "Add to cart" button. The expected catalog is the shared reference
// data in data/shared/products.json (Name A→Z display order).
test.describe('inventory — standard_user', { tag: '@standard' }, () => {
  test.describe('Positive', () => {
    test('all six product images render with distinct, non-empty sources', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      const sources = await inventoryPage.getProductImageSources();
      expect(sources).toHaveLength(products.length);
      expect(sources.every((src) => src.trim().length > 0)).toBe(true);
      // One distinct image per product (contrast with problem_user's shared placeholder).
      expect(new Set(sources).size).toBe(products.length);
    });

    test('all six product titles render exactly and in catalog order', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      expect(await inventoryPage.getProductNames()).toEqual(products.map((p) => p.name));
    });

    test('every product shows its exact description', async ({ inventoryPage }) => {
      await inventoryPage.goto();
      expect(await inventoryPage.getProductDescriptions()).toEqual(
        products.map((p) => p.description),
      );
    });

    test('every product price is formatted with a leading dollar sign', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      const prices = await inventoryPage.getProductPrices();
      expect(prices).toEqual(products.map((p) => p.price));
      expect(prices.every((price) => /^\$\d+\.\d{2}$/.test(price))).toBe(true);
    });

    test('every product offers an enabled Add to cart button', async ({ inventoryPage }) => {
      await inventoryPage.goto();
      expect(await inventoryPage.getAddToCartButtonCount()).toBe(products.length);
      expect(await inventoryPage.getEnabledAddToCartButtonCount()).toBe(products.length);
    });

    // SW-5 — product sorting. The inventory ordering control is a native <select>;
    // expand/collapse of its options (ticket ACs 2 & 3) is browser chrome, not
    // observable in the DOM, so only the sort outcome (AC1) is automated here.
    test('products default to Name (A to Z) order with the matching active sort label', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      const names = await inventoryPage.getProductNames();
      // Default order is ascending by name; no interaction required.
      expect(names).toEqual([...names].sort((a, b) => a.localeCompare(b)));
      expect(await inventoryPage.getActiveSortLabel()).toBe('Name (A to Z)');
    });

    // AC1's four sort modes — one flow (select option → read order), four inputs.
    // The differing read (`getProductNames`/`getProductPrices`) and the expected
    // ordering both live in the table, applied on a single straight-line path, so
    // the body never branches (eslint no-conditional-in-test / no-conditional-expect).
    const toPrice = (p: string): number => parseFloat(p.replace('$', ''));
    const sortScenarios = [
      {
        value: 'az',
        label: 'Name (A to Z)',
        by: 'name ascending',
        read: 'getProductNames',
        sort: (xs: string[]) => [...xs].sort((a, b) => a.localeCompare(b)),
      },
      {
        value: 'za',
        label: 'Name (Z to A)',
        by: 'name descending',
        read: 'getProductNames',
        sort: (xs: string[]) => [...xs].sort((a, b) => b.localeCompare(a)),
      },
      {
        value: 'lohi',
        label: 'Price (low to high)',
        by: 'price ascending',
        read: 'getProductPrices',
        sort: (xs: string[]) => [...xs].sort((a, b) => toPrice(a) - toPrice(b)),
      },
      {
        value: 'hilo',
        label: 'Price (high to low)',
        by: 'price descending',
        read: 'getProductPrices',
        sort: (xs: string[]) => [...xs].sort((a, b) => toPrice(b) - toPrice(a)),
      },
    ] as const;

    for (const { value, label, by, read, sort } of sortScenarios) {
      test(`selecting "${label}" sorts products by ${by}`, async ({ inventoryPage }) => {
        await inventoryPage.goto();
        await inventoryPage.sortBy(value);
        expect(await inventoryPage.getActiveSortLabel()).toBe(label);

        // Displayed order equals those same values sorted in the expected direction
        // (ties, e.g. two $15.99 items, compare equal either way — stable sort).
        const displayed = await inventoryPage[read]();
        expect(displayed).toEqual(sort(displayed));
      });
    }
  });

  test.describe('Edge', () => {
    test('hovering a product title turns its text the brand green (#3ddc91)', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      const productName = products[0].name;
      const restingColor = await inventoryPage.getProductTitleColor(productName);
      expect(restingColor).not.toBe('rgb(61, 220, 145)');
      await inventoryPage.hoverProductTitle(productName);
      // expect.poll re-reads the computed color until it settles, tolerating any CSS transition.
      await expect
        .poll(() => inventoryPage.getProductTitleColor(productName))
        .toBe('rgb(61, 220, 145)');
    });
  });
});
