// Generated by /from-issue on 2026-05-27 from Jira SW-3.
// Source: https://diegocortes15.atlassian.net/browse/SW-3
// Title: [SW][QA][Inventory] problem_user sees broken product images
// Augmented by: SW-4 (2026-05-27)
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { products } from '@data/fixtures';

// problem_user is one of saucedemo's intentionally-broken accounts: the inventory
// page serves the same placeholder image (sl-404) for every product instead of a
// distinct image per product. This characterization test locks that defect in.
test.describe('inventory — problem_user', { tag: '@problem' }, () => {
  test.describe('Edge', () => {
    test('problem_user sees one identical broken image for every product', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      const sources = await inventoryPage.getProductImageSources();
      // Every product image collapses to a single shared src (the broken
      // placeholder) instead of a distinct image per product.
      expect(sources.length).toBeGreaterThan(0);
      expect(new Set(sources).size).toBe(1);
    });
  });
});

// standard_user sees the canonical, fully-rendered inventory: 6 products, each
// with a distinct image, exact title/description, $-formatted price, and an
// enabled "Add to cart" button. The expected catalog is the shared reference
// data in data/shared/products.json (Name A→Z display order).
test.describe('inventory — standard_user', { tag: '@standard' }, () => {
  test.describe('Positive', () => {
    test('all six product images render with distinct, non-empty sources', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      const sources = await inventoryPage.getProductImageSources();
      expect(sources).toHaveLength(products.length);
      expect(sources.every((src) => src.trim().length > 0)).toBe(true);
      // One distinct image per product (contrast with problem_user's shared placeholder).
      expect(new Set(sources).size).toBe(products.length);
    });

    test('all six product titles render exactly and in catalog order', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      expect(await inventoryPage.getProductNames()).toEqual(products.map((p) => p.name));
    });

    test('every product shows its exact description', async ({ inventoryPage }) => {
      await inventoryPage.goto();
      expect(await inventoryPage.getProductDescriptions()).toEqual(
        products.map((p) => p.description),
      );
    });

    test('every product price is formatted with a leading dollar sign', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      const prices = await inventoryPage.getProductPrices();
      expect(prices).toEqual(products.map((p) => p.price));
      expect(prices.every((price) => /^\$\d+\.\d{2}$/.test(price))).toBe(true);
    });

    test('every product offers an enabled Add to cart button', async ({ inventoryPage }) => {
      await inventoryPage.goto();
      expect(await inventoryPage.getAddToCartButtonCount()).toBe(products.length);
      expect(await inventoryPage.getEnabledAddToCartButtonCount()).toBe(products.length);
    });
  });

  test.describe('Edge', () => {
    test('hovering a product title turns its text the brand green (#3ddc91)', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      const productName = products[0].name;
      const restingColor = await inventoryPage.getProductTitleColor(productName);
      expect(restingColor).not.toBe('rgb(61, 220, 145)');
      await inventoryPage.hoverProductTitle(productName);
      // expect.poll re-reads the computed color until it settles, tolerating any CSS transition.
      await expect
        .poll(() => inventoryPage.getProductTitleColor(productName))
        .toBe('rgb(61, 220, 145)');
    });
  });
});
