// Generated by /scaffold-page-object on 2026-06-02.
// Tests using this Page Object are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { test, type Locator, type Page } from '@playwright/test';

// Checkout: Complete! (/checkout-complete.html) — the final checkout step after
// clicking Finish on the overview. Shows the order-confirmation header + body and
// a Back Home button that returns to the inventory page and resets the cart (SW-9).
export class CheckoutCompletePage {
  // Page-direct locators.
  readonly title: Locator;
  // Public so a test can assert the confirmation header/body render (SW-9).
  readonly completeHeader: Locator;
  readonly completeText: Locator;
  // Public so a test can assert it's displayed (SW-9) — mirrors the
  // CartPage.checkoutButton pattern for visibility assertions.
  readonly backHomeButton: Locator;

  constructor(public readonly page: Page) {
    this.title = page.locator('[data-test="title"]');
    this.completeHeader = page.locator('[data-test="complete-header"]');
    this.completeText = page.locator('[data-test="complete-text"]');
    this.backHomeButton = page.locator('[data-test="back-to-products"]');
  }

  // Composed / intent-level action — body wrapped in exactly one test.step.
  async goto(): Promise<void> {
    await test.step('Navigate to the checkout complete page', async () => {
      await this.page.goto('/checkout-complete.html');
    });
  }

  // Composed action — Back Home returns to the inventory page and clears the cart.
  async backHome(): Promise<void> {
    await test.step('Return home from the checkout complete page', async () => {
      await this.backHomeButton.click();
    });
  }

  // Queries — return data, never a Locator (ADR-0001 rule #8).

  /** Page title — "Checkout: Complete!" on this page. */
  async getTitle(): Promise<string> {
    return (await this.title.textContent())?.trim() ?? '';
  }

  /** The order-confirmation header (e.g. "Thank you for your order!"). */
  async getCompleteHeader(): Promise<string> {
    return (await this.completeHeader.textContent())?.trim() ?? '';
  }

  /** The dispatch confirmation body text. */
  async getCompleteText(): Promise<string> {
    return (await this.completeText.textContent())?.trim() ?? '';
  }
}
