// Generated by /scaffold-page-object on 2026-06-02.
// Tests using this Page Object are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { test, type Locator, type Page } from '@playwright/test';

// Checkout: Your Information (/checkout-step-one.html) — the first of saucedemo's
// three checkout steps. Mandatory first name / last name / postal code, with a
// shared error banner and per-field error styling (SW-7).
export class CheckoutInfoPage {
  // Page-direct locators.
  readonly title: Locator;
  readonly firstNameInput: Locator;
  readonly lastNameInput: Locator;
  readonly postalCodeInput: Locator;
  readonly continueButton: Locator;
  // Public so a test can assert visibility / text / hidden state (mirrors
  // LoginPage.errorBanner).
  readonly errorBanner: Locator;
  // The X dismiss control inside the error container — saucedemo exposes no
  // data-test here, so a CSS class is the best available selector.
  private readonly errorDismissButton: Locator;
  // Per-field error indicators: saucedemo adds `error` to each input and renders
  // one `.error_icon` per field when validation fails.
  private readonly erroredInputs: Locator;
  private readonly errorIcons: Locator;

  constructor(public readonly page: Page) {
    this.title = page.locator('[data-test="title"]');
    this.firstNameInput = page.locator('[data-test="firstName"]');
    this.lastNameInput = page.locator('[data-test="lastName"]');
    this.postalCodeInput = page.locator('[data-test="postalCode"]');
    this.continueButton = page.locator('[data-test="continue"]');
    this.errorBanner = page.locator('[data-test="error"]');
    this.errorDismissButton = page.locator('[data-test="error"] button.error-button');
    this.erroredInputs = page.locator('input.error');
    this.errorIcons = page.locator('.error_icon');
  }

  // Primitive — single click, not wrapped in test.step.
  async clickContinue(): Promise<void> {
    await this.continueButton.click();
  }

  // Composed / intent-level actions — body wrapped in exactly one test.step.
  async goto(): Promise<void> {
    await test.step('Navigate to the checkout information page', async () => {
      await this.page.goto('/checkout-step-one.html');
    });
  }

  // Fills the three mandatory fields. Pass '' to leave a field empty (the
  // negative cases populate only a subset).
  async fillInformation(firstName: string, lastName: string, postalCode: string): Promise<void> {
    await test.step('Fill checkout information', async () => {
      await this.firstNameInput.fill(firstName);
      await this.lastNameInput.fill(lastName);
      await this.postalCodeInput.fill(postalCode);
    });
  }

  // Dismisses the error banner via its X control.
  async dismissError(): Promise<void> {
    await test.step('Dismiss the error banner', async () => {
      await this.errorDismissButton.click();
    });
  }

  // Queries — return data, never a Locator (ADR-0001 rule #8).

  async getTitle(): Promise<string> {
    return (await this.title.textContent())?.trim() ?? '';
  }

  async getErrorText(): Promise<string> {
    return (await this.errorBanner.textContent())?.trim() ?? '';
  }

  /** Number of inputs currently flagged with saucedemo's `error` class. */
  async getErroredFieldCount(): Promise<number> {
    return this.erroredInputs.count();
  }

  /** Number of per-field error icons currently rendered. */
  async getErrorIconCount(): Promise<number> {
    return this.errorIcons.count();
  }

  /** Current values of the three fields — used to assert values survive dismiss. */
  async getEnteredValues(): Promise<{ firstName: string; lastName: string; postalCode: string }> {
    return {
      firstName: await this.firstNameInput.inputValue(),
      lastName: await this.lastNameInput.inputValue(),
      postalCode: await this.postalCodeInput.inputValue(),
    };
  }

  /** Placeholder text of the three fields. */
  async getPlaceholders(): Promise<{ firstName: string; lastName: string; postalCode: string }> {
    return {
      firstName: (await this.firstNameInput.getAttribute('placeholder')) ?? '',
      lastName: (await this.lastNameInput.getAttribute('placeholder')) ?? '',
      postalCode: (await this.postalCodeInput.getAttribute('placeholder')) ?? '',
    };
  }
}
