// Generated by /scaffold-page-object on 2026-06-02.
// Tests using this Page Object are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { test, type Locator, type Page } from '@playwright/test';

// Checkout: Overview (/checkout-step-two.html) — the second checkout step.
// SW-7 only needs to confirm the user lands here after a valid information
// submission, so this is intentionally minimal; later tickets grow it.
export class CheckoutOverviewPage {
  // Page-direct locators.
  readonly title: Locator;

  constructor(public readonly page: Page) {
    this.title = page.locator('[data-test="title"]');
  }

  // Composed / intent-level action — body wrapped in exactly one test.step.
  async goto(): Promise<void> {
    await test.step('Navigate to the checkout overview page', async () => {
      await this.page.goto('/checkout-step-two.html');
    });
  }

  // Query — returns data, never a Locator (ADR-0001 rule #8).
  async getTitle(): Promise<string> {
    return (await this.title.textContent())?.trim() ?? '';
  }
}
