// Generated by /scaffold-page-object on 2026-06-02.
// Tests using this Page Object are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { test, type Locator, type Page } from '@playwright/test';
import { Header } from '@components/Header';

// Checkout step one — "Checkout: Your Information" (/checkout-step-one.html).
// Composes the shared Header (cart icon + badge) and holds the page-direct
// form fields + the Cancel/Continue controls. The Continue/error surface is
// modelled too so a later validation ticket can reuse this page object.
export class CheckoutInfoPage {
  // Composed components first (ADR-0001 rule #6).
  readonly header: Header;
  // Page-direct locators second. cancelButton is public so a test can assert
  // its visibility (per the LoginPage.errorBanner pattern).
  readonly cancelButton: Locator;
  private readonly firstNameInput: Locator;
  private readonly lastNameInput: Locator;
  private readonly postalCodeInput: Locator;
  private readonly continueButton: Locator;
  private readonly errorBanner: Locator;

  constructor(public readonly page: Page) {
    this.header = new Header(page);
    this.cancelButton = page.locator('[data-test="cancel"]');
    this.firstNameInput = page.locator('[data-test="firstName"]');
    this.lastNameInput = page.locator('[data-test="lastName"]');
    this.postalCodeInput = page.locator('[data-test="postalCode"]');
    this.continueButton = page.locator('[data-test="continue"]');
    this.errorBanner = page.locator('[data-test="error"]');
  }

  // The shared header cart icon, surfaced so a test can assert its visibility.
  get cartIcon(): Locator {
    return this.header.cartLink;
  }

  // Composed / intent-level action — body wrapped in exactly one test.step.
  async goto(): Promise<void> {
    await test.step('Navigate to the checkout information page', async () => {
      await this.page.goto('/checkout-step-one.html');
    });
  }

  // Primitive — single-element action, never wrapped in test.step.
  async clickContinue(): Promise<void> {
    await this.continueButton.click();
  }

  // Composed action — fill the three required fields in one named step.
  async fillInformation(firstName: string, lastName: string, postalCode: string): Promise<void> {
    await test.step('Fill the checkout information form', async () => {
      await this.firstNameInput.fill(firstName);
      await this.lastNameInput.fill(lastName);
      await this.postalCodeInput.fill(postalCode);
    });
  }

  // Composed action — cancel back to the cart page.
  async cancel(): Promise<void> {
    await test.step('Cancel the checkout', async () => {
      await this.cancelButton.click();
    });
  }

  // Composed action — open the cart from the shared header icon.
  async openCart(): Promise<void> {
    await this.header.openCart();
  }

  // Queries — return data, never a Locator (ADR-0001 rule #8).

  /** Current value of each form field (empty string when unset). */
  async getFirstName(): Promise<string> {
    return this.firstNameInput.inputValue();
  }

  async getLastName(): Promise<string> {
    return this.lastNameInput.inputValue();
  }

  async getPostalCode(): Promise<string> {
    return this.postalCodeInput.inputValue();
  }

  /** Validation banner text; '' when no banner is shown. */
  async getErrorText(): Promise<string> {
    return (await this.errorBanner.textContent())?.trim() ?? '';
  }
}
