// Generated by /from-issue on 2026-06-02 from Jira SW-8.
// Source: https://diegocortes15.atlassian.net/browse/SW-8
// Title: [SW][QA][Checkout] User fill mandatory information - part 2
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';

test.describe('checkout — standard_user', { tag: '@standard' }, () => {
  test.describe('Positive', () => {
    // AC 1 + AC 2 (merged): both controls are present on page load.
    test('the cancel button and header cart icon are visible', async ({ checkoutInfoPage }) => {
      await checkoutInfoPage.goto();
      await expect(checkoutInfoPage.cancelButton).toBeVisible();
      await expect(checkoutInfoPage.cartIcon).toBeVisible();
    });

    // AC 3 + AC 4 (merged): both exit controls return the user to the cart page.
    for (const exit of ['cancel', 'cart'] as const) {
      const label = exit === 'cancel' ? 'the cancel button' : 'the header cart icon';
      test(`clicking ${label} returns to the cart page`, async ({ checkoutInfoPage, page }) => {
        await checkoutInfoPage.goto();
        if (exit === 'cancel') {
          await checkoutInfoPage.cancel();
        } else {
          await checkoutInfoPage.openCart();
        }
        await expect(page).toHaveURL(/\/cart\.html$/);
      });
    }

    // AC 5: saucedemo does not persist the form — leaving and returning shows it empty.
    test('the information form is reset after leaving and returning', async ({
      checkoutInfoPage,
    }) => {
      await checkoutInfoPage.goto();
      await checkoutInfoPage.fillInformation('Jane', 'Doe', '12345');
      await checkoutInfoPage.cancel();
      await checkoutInfoPage.goto();

      expect(await checkoutInfoPage.getFirstName()).toBe('');
      expect(await checkoutInfoPage.getLastName()).toBe('');
      expect(await checkoutInfoPage.getPostalCode()).toBe('');
    });
  });

  test.describe('Edge', () => {
    // AC 6: Cancel does NOT enforce the required-field validation Continue does —
    // an empty form still returns to the cart cleanly.
    test('cancelling with an empty form returns to the cart without a validation error', async ({
      checkoutInfoPage,
      page,
    }) => {
      await checkoutInfoPage.goto();
      await checkoutInfoPage.cancel();
      await expect(page).toHaveURL(/\/cart\.html$/);
    });
  });
});
