// Generated by /from-issue on 2026-06-02 from Jira SW-7.
// Source: https://diegocortes15.atlassian.net/browse/SW-7
// Title: [SW][QA][Checkout] User fill mandatory information
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';

const BACKPACK = 'Sauce Labs Backpack';
const VALID_INFO = { firstName: 'John', lastName: 'Doe', postalCode: '12345' } as const;

test.describe('checkout — standard_user', { tag: '@standard' }, () => {
  test.describe('Positive', () => {
    // AC 1 + AC 2: the cart's Checkout button is shown and lands on the
    // Checkout: Your Information page.
    test('checkout button on the cart page navigates to Checkout: Your Information', async ({
      inventoryPage,
      cartPage,
      checkoutInfoPage,
      page,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();

      await expect(cartPage.checkoutButton).toBeVisible();
      await cartPage.checkout();

      await expect(page).toHaveURL(/\/checkout-step-one\.html$/);
      expect(await checkoutInfoPage.getTitle()).toBe('Checkout: Your Information');
    });

    // AC 8: the three mandatory inputs render their placeholder text.
    test('mandatory fields show their placeholder text', async ({ checkoutInfoPage }) => {
      await checkoutInfoPage.goto();
      expect(await checkoutInfoPage.getPlaceholders()).toEqual({
        firstName: 'First Name',
        lastName: 'Last Name',
        postalCode: 'Zip/Postal Code',
      });
    });

    // AC 9: a complete, valid information form routes to Checkout: Overview.
    test('valid information routes to Checkout: Overview', { tag: '@smoke' }, async ({
      inventoryPage,
      cartPage,
      checkoutInfoPage,
      checkoutOverviewPage,
      page,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();
      await cartPage.checkout();

      await checkoutInfoPage.fillInformation(
        VALID_INFO.firstName,
        VALID_INFO.lastName,
        VALID_INFO.postalCode,
      );
      await checkoutInfoPage.clickContinue();

      await expect(page).toHaveURL(/\/checkout-step-two\.html$/);
      expect(await checkoutOverviewPage.getTitle()).toBe('Checkout: Overview');
    });
  });

  test.describe('Negative', () => {
    // AC 3–6: saucedemo validates required fields sequentially (First → Last →
    // Zip), reports the first missing one, and flags all three inputs at once.
    const validationCases = [
      { desc: 'all fields empty', firstName: '', lastName: '', postalCode: '', error: 'Error: First Name is required' },
      { desc: 'only first name', firstName: 'John', lastName: '', postalCode: '', error: 'Error: Last Name is required' },
      { desc: 'only last name', firstName: '', lastName: 'Doe', postalCode: '', error: 'Error: First Name is required' },
      { desc: 'only postal code', firstName: '', lastName: '', postalCode: '12345', error: 'Error: First Name is required' },
    ];

    for (const { desc, firstName, lastName, postalCode, error } of validationCases) {
      test(`continue with ${desc} shows "${error}" and flags all fields`, async ({
        checkoutInfoPage,
      }) => {
        await checkoutInfoPage.goto();
        await checkoutInfoPage.fillInformation(firstName, lastName, postalCode);
        await checkoutInfoPage.clickContinue();

        await expect(checkoutInfoPage.errorBanner).toHaveText(error);
        await expect.poll(() => checkoutInfoPage.getErroredFieldCount()).toBe(3);
        await expect.poll(() => checkoutInfoPage.getErrorIconCount()).toBe(3);
      });
    }
  });

  test.describe('Edge', () => {
    // AC 7: dismissing the error clears the banner and the per-field error
    // styling, while preserving whatever the user already typed.
    test('dismissing the error clears the banner and field styling but keeps entered values', async ({
      checkoutInfoPage,
    }) => {
      await checkoutInfoPage.goto();
      await checkoutInfoPage.fillInformation('John', '', '');
      await checkoutInfoPage.clickContinue();
      await expect(checkoutInfoPage.errorBanner).toBeVisible();
      await expect.poll(() => checkoutInfoPage.getErroredFieldCount()).toBe(3);

      await checkoutInfoPage.dismissError();
      await expect(checkoutInfoPage.errorBanner).toBeHidden();
      await expect.poll(() => checkoutInfoPage.getErroredFieldCount()).toBe(0);
      await expect.poll(() => checkoutInfoPage.getErrorIconCount()).toBe(0);
      expect((await checkoutInfoPage.getEnteredValues()).firstName).toBe('John');
    });
  });
});
