// Generated by /scaffold-page-object on 2026-05-26.
// Tests using this component are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { type Locator, type Page } from '@playwright/test';

// The saucedemo footer is DOM-identical on every authenticated page
// (data-test="footer"), so it lives as a shared component rather than
// page-direct locators.
export type SocialNetwork = 'twitter' | 'facebook' | 'linkedin';

export class Footer {
  readonly root: Locator;
  private readonly copyright: Locator;
  private readonly socialLinks: Record<SocialNetwork, Locator>;

  constructor(public readonly page: Page) {
    this.root = page.locator('[data-test="footer"]');
    this.copyright = page.locator('[data-test="footer-copy"]');
    this.socialLinks = {
      twitter: page.locator('[data-test="social-twitter"]'),
      facebook: page.locator('[data-test="social-facebook"]'),
      linkedin: page.locator('[data-test="social-linkedin"]'),
    };
  }

  // Queries — return data, never a Locator (ADR-0001 rule #8).
  async getSocialLinkHref(network: SocialNetwork): Promise<string> {
    return (await this.socialLinks[network].getAttribute('href')) ?? '';
  }

  async getCopyrightText(): Promise<string> {
    return (await this.copyright.textContent())?.trim() ?? '';
  }
}
