// Generated by /from-issue on 2026-06-03 from Jira SW-11.
// Source: https://diegocortes15.atlassian.net/browse/SW-11
// Title: [SW][QA][Burger] User options
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';

// The burger-menu options behave identically for every authenticated user, so
// they are verified once as standard_user (@standard) — the same "verify once"
// choice the footer spec makes. Logout (the panel's 4th option) is intentionally
// out of scope here: SW-10 already covers it in tests/logout/logout.spec.ts.
test.describe('burger_menu — standard_user', { tag: '@standard' }, () => {
  test.describe('Positive', () => {
    // AC 1 — opening the panel surfaces the three in-scope options.
    test('burger menu lists the All Items, About, and Reset App State options', async ({
      inventoryPage,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.header.burgerMenu.open();
      await expect(inventoryPage.header.burgerMenu.allItemsOption).toBeVisible();
      await expect(inventoryPage.header.burgerMenu.aboutOption).toBeVisible();
      await expect(inventoryPage.header.burgerMenu.resetAppStateOption).toBeVisible();
    });

    // AC 2 — "All Items" lands on the inventory page (URL + "Products" title).
    test('All Items returns to the inventory page', async ({ inventoryPage, page }) => {
      await inventoryPage.goto();
      await inventoryPage.header.burgerMenu.open();
      await inventoryPage.header.burgerMenu.selectAllItems();
      await expect(page).toHaveURL(/\/inventory\.html$/);
      expect(await inventoryPage.getTitle()).toBe('Products');
    });

    // AC 3 — "About" navigates the SAME tab to saucelabs.com. This is a real
    // third-party navigation (the ticket's explicit choice over the footer's
    // href-only convention), so it depends on the external site being reachable.
    test('About navigates the same tab to saucelabs.com', async ({ inventoryPage, page }) => {
      await inventoryPage.goto();
      await inventoryPage.header.burgerMenu.open();
      await inventoryPage.header.burgerMenu.selectAbout();
      await expect(page).toHaveURL(/saucelabs\.com/, { timeout: 15_000 });
    });

    // AC 4 — "Reset App State" clears the cart: after a refresh the badge is
    // gone, both products show "Add to cart" again, and the cart is empty.
    test('Reset App State clears the cart badge, reverts buttons, and empties the cart', async ({
      inventoryPage,
      cartPage,
    }) => {
      const backpack = 'Sauce Labs Backpack';
      const bikeLight = 'Sauce Labs Bike Light';

      await inventoryPage.goto();
      await inventoryPage.addToCart(backpack);
      await inventoryPage.addToCart(bikeLight);
      expect(await inventoryPage.getCartBadgeCount()).toBe(2);

      await inventoryPage.header.burgerMenu.open();
      await inventoryPage.header.burgerMenu.resetAppState();
      // saucedemo only reverts the product buttons after a reload (the ticket
      // calls this out explicitly), so refresh before re-checking state.
      await inventoryPage.goto();

      expect(await inventoryPage.getCartBadgeCount()).toBe(0);
      expect(await inventoryPage.getProductButtonLabel(backpack)).toBe('Add to cart');
      expect(await inventoryPage.getProductButtonLabel(bikeLight)).toBe('Add to cart');

      await cartPage.goto();
      expect(await cartPage.getItemCount()).toBe(0);
    });
  });

  test.describe('Edge', () => {
    // AC 5 — the close (X) button hides the panel options again.
    test('the close button hides the burger menu options', async ({ inventoryPage }) => {
      await inventoryPage.goto();
      await inventoryPage.header.burgerMenu.open();
      await expect(inventoryPage.header.burgerMenu.allItemsOption).toBeVisible();
      await inventoryPage.header.burgerMenu.close();
      await expect(inventoryPage.header.burgerMenu.allItemsOption).toBeHidden();
    });

    // AC 6 — "All Items" from the cart page also returns to the inventory page.
    test('All Items from the cart page returns to the inventory page', async ({
      cartPage,
      page,
    }) => {
      await cartPage.goto();
      await cartPage.header.burgerMenu.open();
      await cartPage.header.burgerMenu.selectAllItems();
      await expect(page).toHaveURL(/\/inventory\.html$/);
    });
  });
});
