// Generated by /from-issue on 2026-06-03 from Jira SW-10.
// Source: https://diegocortes15.atlassian.net/browse/SW-10
// Title: [SW][QA][Logout] User logout
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { env } from '@utils/env';

// One @no-auth context: each test establishes (and tears down) its own session,
// matching the ticket's "After the user logs in successfully:" framing and the
// existing login.spec 5-user-loop precedent — so no storageState/harness growth
// is needed to cover every login-capable user.
test.describe('logout — no auth', { tag: '@no-auth' }, () => {
  test.describe('Positive', () => {
    // AC 1 — every login-capable user logs out via the header burger menu and is
    // returned to the login screen. locked_out_user is excluded: it can never
    // authenticate, so it never reaches a logged-in state to log out from.
    const users = [
      'standard_user',
      'problem_user',
      'performance_glitch_user',
      'error_user',
      'visual_user',
    ];

    for (const user of users) {
      test(
        `${user} logs out from the menu and returns to the login page`,
        user === 'standard_user' ? { tag: '@smoke' } : {},
        async ({ loginPage, inventoryPage, page }) => {
          await loginPage.goto();
          await loginPage.loginAs(user, env.password);
          // Generous timeout: performance_glitch_user adds a ~10s navigation delay.
          await expect(page).toHaveURL(/\/inventory\.html$/, { timeout: 15_000 });
          await inventoryPage.logout();
          await expect(page).toHaveURL(/\/$/, { timeout: 15_000 });
          await expect(loginPage.loginButton).toBeVisible();
        },
      );
    }
  });

  test.describe('Negative', () => {
    // AC 2 — with no active session, directly opening a protected page redirects
    // to the login screen, shows the page-specific guard error, and flags both
    // credential fields with error styling.
    const protectedPages = [
      {
        path: '/inventory.html',
        error: "Epic sadface: You can only access '/inventory.html' when you are logged in.",
      },
      {
        path: '/cart.html',
        error: "Epic sadface: You can only access '/cart.html' when you are logged in.",
      },
      {
        path: '/checkout-step-one.html',
        error: "Epic sadface: You can only access '/checkout-step-one.html' when you are logged in.",
      },
      {
        path: '/checkout-step-two.html',
        error: "Epic sadface: You can only access '/checkout-step-two.html' when you are logged in.",
      },
      {
        path: '/checkout-complete.html',
        error: "Epic sadface: You can only access '/checkout-complete.html' when you are logged in.",
      },
    ];

    for (const { path, error } of protectedPages) {
      test(
        `direct access to ${path} while logged out is blocked with an error`,
        path === '/inventory.html' ? { tag: '@smoke' } : {},
        async ({ loginPage, page }) => {
          await loginPage.gotoProtected(path);
          await expect(page).toHaveURL(/\/$/);
          await expect(loginPage.errorBanner).toHaveText(error);
          await expect(loginPage.usernameInput).toHaveClass(/error/);
          await expect(loginPage.passwordInput).toHaveClass(/error/);
        },
      );
    }
  });

  test.describe('Edge', () => {
    // AC 3 — after logout, the browser Back button must not restore the session:
    // the route guard redirects to the login screen with its error instead of
    // re-showing the previously authenticated page.
    test('back button after logout does not restore the session', async ({
      loginPage,
      inventoryPage,
      page,
    }) => {
      await loginPage.goto();
      await loginPage.loginAs('standard_user', env.password);
      await expect(page).toHaveURL(/\/inventory\.html$/);
      await inventoryPage.logout();
      await page.goBack();
      await expect(page).toHaveURL(/\/$/);
      await expect(loginPage.errorBanner).toBeVisible();
    });
  });
});
