// Generated by /from-issue on 2026-09-06 from Jira SW-12.
// Source: https://diegocortes15.atlassian.net/browse/SW-12
// Title: [SW][QA][Product detail] standard_user opens a product's detail page
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { products } from '@data/fixtures';

// The ticket names "Sauce Labs Backpack" for every AC. It is the first entry of the
// shared catalog, so the expected name/description/price come from reference data
// rather than being restated here (data-placement.md — reused ⇒ already externalized).
const [backpack] = products;

test.describe('product_detail — standard_user', { tag: '@standard' }, () => {
  test.describe('Positive', () => {
    test('product detail page shows the selected product name, description and price', async ({
      inventoryPage,
      productDetailPage,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.openProductDetail(backpack.name);

      expect(await productDetailPage.getProductName()).toBe(backpack.name);
      expect(await productDetailPage.getProductDescription()).toBe(backpack.description);
      expect(await productDetailPage.getProductPrice()).toBe(backpack.price);
    });

    test('adding to cart from the product detail page updates the header cart badge', async ({
      inventoryPage,
      productDetailPage,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.openProductDetail(backpack.name);

      // saucedemo renders no badge at all for an empty cart, so getCartBadgeCount()
      // reports 0 for "absent" (see CartBadge).
      expect(await productDetailPage.getCartBadgeCount()).toBe(0);

      await productDetailPage.clickAddToCart();
      expect(await productDetailPage.getCartBadgeCount()).toBe(1);
    });

    test('back to products returns to the inventory page with the full catalog', async ({
      inventoryPage,
      productDetailPage,
      page,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.openProductDetail(backpack.name);

      await productDetailPage.clickBackToProducts();

      await expect(page).toHaveURL(/\/inventory\.html$/);
      expect(await inventoryPage.getProductNames()).toHaveLength(products.length);
    });
  });
});
